//! Registry loading and load-time validation (spec §7).
//!
//! A **registry** defines measurement itself — dimensions and units. A
//! **vocabulary** defines domain meaning — quantity kinds only (§3, §7.4). One
//! registry is loaded per deployment; many vocabularies may be.
//!
//! Validation is not optional decoration. §7.4 makes federation the normal
//! case, so third-party artifacts reach the resolution path that canonical form
//! and every conversion factor depend on. A *signed* catalog is attributable,
//! not conformant — so these checks run regardless of seal state, and their
//! failures are never phrased as trust failures.



use alloc::borrow::Cow;
use alloc::collections::BTreeMap;
use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec;
use alloc::vec::Vec;

use crate::dimension::Dimension;
use crate::error::{Error, ErrorCode, Result};
use crate::rational::{Rational, Scale};
use crate::toml_lite::{self, Value};

#[derive(Clone, Debug)]
pub struct DisplayForms {
    pub unicode: Option<String>,
    pub ascii: Option<String>,
    pub latex: Option<String>,
    pub long: Option<String>,
    pub plural: Option<String>,
}

impl DisplayForms {
    /// The form a human-facing label should prefer.
    pub fn preferred<'a>(&'a self, symbol: &'a str) -> &'a str {
        self.unicode.as_deref().unwrap_or(symbol)
    }
}

#[derive(Clone, Debug)]
pub struct Unit {
    pub symbol: String,
    pub dimension_name: String,
    pub dimension: Dimension,
    /// Exact scale to the dimension's base unit — a rational, optionally times
    /// an integer power of π (§7.2). Almost every unit has a π exponent of 0.
    pub factor: Scale,
    /// Exact rational intercept, **in the dimension's base unit** (§6.4, as
    /// ruled). Presence makes the unit affine.
    pub offset: Option<Rational>,
    pub delta: Option<String>,
    pub display: DisplayForms,
    /// Set on an entry generated by prefix expansion — carries the base symbol
    /// it was derived from, so the docs and error messages can say so.
    pub prefixed_from: Option<String>,
    /// §7.2 `provenance`: where this definition came from, and under which
    /// measurement convention.
    ///
    /// Carried per unit rather than per registry because real registries are
    /// mixed — this one holds SI (`W`, `V`, `J`), US customary (`Btu`, `mi`),
    /// and metric-but-not-SI (`t`, `h`, `deg`) side by side, so no single
    /// registry-level label would be true. And a *behavioural* one would be
    /// worse than useless: if `M` meant 10^6 in one registry and 10^3 in
    /// another, the same canonical string would denote different quantities
    /// and §6.3 would stop being an equality primitive.
    pub provenance: Provenance,
}

/// A spelling this registry deliberately refuses, and why.
///
/// Distinct from a symbol that is merely absent. `MBtu` is not a typo — it is a
/// string two conventions read differently (10^6 under SI prefixes, 10^3 in the
/// US gas industry), so resolving it either way would be guessing. Refusing it
/// is correct; refusing it with `E_UNKNOWN_UNIT — did you mean MMBtu?` throws
/// away the reason and leaves the user to rediscover it.
///
/// The registry author knows why. This is where they say so, once, and both the
/// error message and the generated documentation are built from it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Ambiguity {
    /// Why the spelling is refused. Required — a refusal without a reason is
    /// the failure this type exists to prevent.
    pub reason: String,
    /// What to write instead. Actionable, so the message ends with a fix.
    pub use_instead: Vec<String>,
    /// Where to read more.
    pub see: Option<String>,
}

impl Ambiguity {
    /// The refusal, as a user should read it.
    pub fn describe(&self, symbol: &str) -> String {
        let mut s = format!("{symbol:?} is ambiguous and is refused rather than guessed: {}", self.reason);
        match self.use_instead.len() {
            0 => {}
            1 => s.push_str(&format!(" Write `{}` instead.", self.use_instead[0])),
            _ => s.push_str(&format!(
                " Write one of {} instead.",
                self.use_instead.iter().map(|u| format!("`{u}`")).collect::<Vec<_>>().join(", ")
            )),
        }
        if let Some(see) = &self.see {
            s.push_str(&format!(" See {see}"));
        }
        s
    }
}

/// Where a unit's definition came from (§7.2).
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Provenance {
    /// The measurement convention this definition follows — `"si"`,
    /// `"us-customary"`, `"imperial"`, `"iec"`, and so on. Free text: the
    /// registry states it, nothing infers it.
    pub system: Option<String>,
    pub source: Option<String>,
    pub scope: Option<String>,
    pub note: Option<String>,
}

impl Provenance {
    pub fn is_empty(&self) -> bool {
        self.system.is_none()
            && self.source.is_none()
            && self.scope.is_none()
            && self.note.is_none()
    }
}

impl Unit {
    pub fn is_affine(&self) -> bool {
        self.offset.is_some()
    }

    /// Affine units and `pu` are non-composable: their meaning depends on
    /// something a compound expression cannot carry (an arbitrary zero, or an
    /// external base).
    pub fn is_non_composable(&self) -> bool {
        self.is_affine() || self.symbol == "pu"
    }

    pub fn offset_or_zero(&self) -> Rational {
        self.offset.unwrap_or(Rational::ZERO)
    }
}

#[derive(Clone, Debug, Default)]
pub struct QuantityKind {
    pub id: String,
    pub parent: Option<String>,
    pub interval: Option<bool>,
    pub rate_of: Option<String>,
    pub summable_with: Vec<String>,
    pub display_long: Option<String>,
}

/// A symbol that two readings can both produce: an authored unit, and a base
/// unit carrying a prefix.
///
/// Reported so a registry developer can see the whole contested set at once,
/// rather than discovering it one load error at a time.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CollisionRisk {
    /// The contested spelling, e.g. `ft`.
    pub symbol: String,
    /// The authored unit's dimension, if one is declared for this spelling.
    pub authored: Option<String>,
    /// The prefix symbol that produces it, e.g. `f`.
    pub prefix: &'static str,
    /// The prefix's long name, e.g. `femto`.
    pub prefix_long: &'static str,
    /// The base symbol it attaches to, e.g. `t`.
    pub base: String,
    /// Whether the registry has resolved it via `prefix_collisions`.
    pub resolved: bool,
    /// Why the authored reading won, as the registry author stated it.
    ///
    /// `Some` exactly when `resolved` — the declaration and its reason are one
    /// thing, so a resolved collision can never be reported without its
    /// justification, which is the point of requiring it.
    pub reason: Option<String>,
}

#[derive(Clone, Debug)]
pub struct Registry {
    pub name: String,
    pub version: String,
    pub schema_version: i128,
    units: BTreeMap<String, Unit>,
    aliases: BTreeMap<String, String>,
    dimensions: BTreeMap<String, Dimension>,
    quantities: BTreeMap<String, QuantityKind>,
    /// Symbol → the author's stated reason, for spellings where an authored
    /// unit deliberately wins over a prefixed form that would produce the same
    /// one. Declared, never inferred.
    shadowed: BTreeMap<String, String>,
    /// Spellings this registry refuses on purpose, with the reason.
    ambiguous: BTreeMap<String, Ambiguity>,
    /// Base symbol → prefix set. Prefixed units are **derived on lookup**, not
    /// stored: 20 authored units with the full SI set would otherwise become 500
    /// entries and 1049 aliases, a 50× amplification of a 3 KB source file. The
    /// combinations are still enumerated at load time — for collision checking
    /// only — so ambiguity remains impossible by construction.
    prefixable: BTreeMap<String, &'static [crate::prefix::Prefix]>,
}

fn invalid(msg: impl Into<String>) -> Error {
    Error::new(ErrorCode::RegistryInvalid, msg)
}

impl Registry {
    pub fn from_toml(src: &str) -> Result<Registry> {
        let doc = toml_lite::parse(src).map_err(|e| invalid(format!("not valid TOML: {e}")))?;

        // ---- header (§7.1) ----
        let header = doc
            .get("registry")
            .and_then(Value::as_table)
            .ok_or_else(|| invalid("missing [registry] header"))?;
        let name = header
            .get("name")
            .and_then(Value::as_str)
            .ok_or_else(|| invalid("[registry].name is required — a version without a name identifies nothing"))?
            .to_string();
        if name.is_empty() || !name.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-') {
            return Err(invalid(format!("[registry].name {name:?} must match [a-z0-9-]+")));
        }
        let version = header
            .get("version")
            .and_then(Value::as_str)
            .ok_or_else(|| invalid("[registry].version is required"))?
            .to_string();
        // Collisions between an authored symbol and a prefixed form are a
        // load error *unless* the author resolves them here. One table, so
        // "where did this registry make a judgement call?" has one answer — and
        // the value is the *reason*, required rather than optional. The decision
        // sits far from the `[unit.…]` entry it silently affects, so a diff of
        // that entry cannot show it; without a recorded reason a reviewer has to
        // reconstruct the judgement from two distant places, and a later
        // maintainer has nothing to weigh when the trade-off shifts.
        let mut shadow_decls: BTreeMap<String, String> = BTreeMap::new();
        if let Some(v) = header.get("prefix_collisions") {
            let table = v.as_table().ok_or_else(|| {
                invalid(
                    "[registry].prefix_collisions must be a table of symbol = \"reason\", e.g. \
                     `[registry.prefix_collisions]` then `ft = \"foot is far more common here \
                     than femto-tonne\"`. A bare list records the decision without the \
                     judgement behind it",
                )
            })?;
            for (symbol, reason) in table {
                let reason = reason.as_str().ok_or_else(|| {
                    invalid(format!(
                        "[registry.prefix_collisions].{symbol} must be a string explaining why \
                         the authored unit wins this spelling"
                    ))
                })?;
                if reason.trim().is_empty() {
                    return Err(invalid(format!(
                        "[registry.prefix_collisions].{symbol} has an empty reason; state why \
                         the authored reading wins, because this line is the only record of it"
                    )));
                }
                shadow_decls.insert(symbol.clone(), reason.to_string());
            }
        }

        // Spellings the author knows are traps. Read before units, so a
        // declaration for a symbol the registry also defines can be rejected.
        let mut ambiguous: BTreeMap<String, Ambiguity> = BTreeMap::new();
        if let Some(v) = header.get("ambiguous") {
            let table = v.as_table().ok_or_else(|| {
                invalid("[registry.ambiguous] must be a table of symbol = { reason = \"…\" }")
            })?;
            for (symbol, body) in table {
                let t = body.as_table().ok_or_else(|| {
                    invalid(format!(
                        "[registry.ambiguous].{symbol} must be a table with at least a `reason`"
                    ))
                })?;
                let reason = t
                    .get("reason")
                    .and_then(Value::as_str)
                    .filter(|r| !r.trim().is_empty())
                    .ok_or_else(|| {
                        invalid(format!(
                            "[registry.ambiguous].{symbol} needs a non-empty `reason`; refusing a \
                             spelling without saying why leaves the user to rediscover it"
                        ))
                    })?
                    .to_string();
                let use_instead = t
                    .get("use")
                    .and_then(Value::as_array)
                    .map(|a| a.iter().filter_map(Value::as_str).map(str::to_string).collect())
                    .unwrap_or_default();
                let see = t.get("see").and_then(Value::as_str).map(str::to_string);
                ambiguous.insert(symbol.clone(), Ambiguity { reason, use_instead, see });
            }
        }

        let schema_version = header
            .get("schema_version")
            .and_then(Value::as_integer)
            .ok_or_else(|| invalid("[registry].schema_version is required"))?;

        // ---- dimensions (§6.2, §7.2) ----
        let mut dimensions = BTreeMap::new();
        if let Some(dims) = doc.get("dimension").and_then(Value::as_table) {
            for (dim_name, body) in dims {
                let vector = body
                    .as_table()
                    .and_then(|t| t.get("vector"))
                    .and_then(Value::as_table)
                    .ok_or_else(|| invalid(format!("[dimension.{dim_name}] needs a `vector` table")))?;
                let mut d = Dimension::DIMENSIONLESS;
                for (base, exp) in vector {
                    let idx = Dimension::index_of(base).ok_or_else(|| {
                        invalid(format!(
                            "[dimension.{dim_name}] references unknown base dimension {base:?}; \
                             the nine base dimensions are fixed (§6.2)"
                        ))
                    })?;
                    let e = exp
                        .as_integer()
                        .filter(|v| *v >= i8::MIN as i128 && *v <= i8::MAX as i128)
                        .ok_or_else(|| {
                            invalid(format!(
                                "[dimension.{dim_name}] exponent for {base:?} is outside the \
                                 signed 8-bit range"
                            ))
                        })?;
                    d.set(idx, e as i8);
                }
                // Declaring a dimension that *shares a base dimension's name* is
                // only legal as an identity — `[dimension.length] vector =
                // { length = 1 }` is redundant but harmless. Anything else is a
                // redefinition of a frozen base dimension (§6.2) and is the
                // sharpest form of the catalog-shadowing attack: it silently
                // changes what every commensurability check means.
                if let Some(idx) = Dimension::index_of(dim_name) {
                    let mut identity = Dimension::DIMENSIONLESS;
                    identity.set(idx, 1);
                    if d != identity {
                        return Err(invalid(format!(
                            "[dimension.{dim_name}] redefines base dimension {dim_name:?} as \
                             {d:?}; the nine base dimensions are frozen (§6.2)"
                        )));
                    }
                }
                dimensions.insert(dim_name.clone(), d);
            }
        }

        // ---- units (§7.2) ----
        let mut units: BTreeMap<String, Unit> = BTreeMap::new();
        let mut aliases: BTreeMap<String, String> = BTreeMap::new();
        let mut prefixable_decls: Vec<(String, String)> = Vec::new();
        if let Some(us) = doc.get("unit").and_then(Value::as_table) {
            for (symbol, body) in us {
                validate_symbol(symbol, "unit symbol")?;
                let t = body
                    .as_table()
                    .ok_or_else(|| invalid(format!("[unit.{symbol}] is not a table")))?;

                for key in t.keys() {
                    // Typo protection: `factr = [1000, 1]` would otherwise load
                    // silently as a unit with no factor.
                    const KNOWN: [&str; 10] = [
                        "dimension", "factor", "offset", "delta", "aliases", "display",
                        "prefixes", "provenance", "variants", "pi",
                    ];
                    if !KNOWN.contains(&key.as_str()) {
                        return Err(invalid(format!("[unit.{symbol}] has unknown key {key:?}")));
                    }
                }

                let dim_name = t
                    .get("dimension")
                    .and_then(Value::as_str)
                    .ok_or_else(|| invalid(format!("[unit.{symbol}] needs a `dimension`")))?;
                let dimension = if let Some(d) = dimensions.get(dim_name) {
                    *d
                } else if let Some(idx) = Dimension::index_of(dim_name) {
                    let mut d = Dimension::DIMENSIONLESS;
                    d.set(idx, 1);
                    d
                } else if dim_name == "dimensionless" {
                    Dimension::DIMENSIONLESS
                } else {
                    return Err(invalid(format!(
                        "[unit.{symbol}] references undefined dimension {dim_name:?}"
                    )));
                };

                let (fnum, fden) = t
                    .get("factor")
                    .and_then(Value::as_pair)
                    .ok_or_else(|| {
                        invalid(format!(
                            "[unit.{symbol}].factor must be an exact rational [numerator, denominator]"
                        ))
                    })?;
                if fden == 0 {
                    return Err(invalid(format!("[unit.{symbol}].factor has a zero denominator")));
                }
                if fnum == 0 {
                    return Err(invalid(format!(
                        "[unit.{symbol}].factor is zero; a zero scale is never a unit"
                    )));
                }
                if (fnum < 0) != (fden < 0) {
                    return Err(invalid(format!(
                        "[unit.{symbol}].factor is negative; a negative scale is never a unit"
                    )));
                }
                if !Rational::is_reduced(fnum, fden) {
                    return Err(invalid(format!(
                        "[unit.{symbol}].factor [{fnum}, {fden}] is not in lowest terms; \
                         unreduced pairs overflow under exponentiation"
                    )));
                }
                let ratio = Rational::new(fnum, fden)
                    .ok_or_else(|| invalid(format!("[unit.{symbol}].factor is not representable")))?;
                // An optional integer power of π (§7.2). This is what lets a
                // degree be *exactly* `(1/180)·π` radians instead of a stored
                // rounding of an irrational number — see AMB-066.
                let pi = match t.get("pi") {
                    None => 0,
                    Some(v) => {
                        let e = v.as_integer().filter(|e| (-8..=8).contains(e)).ok_or_else(|| {
                            invalid(format!(
                                "[unit.{symbol}].pi must be a small integer exponent of π; \
                                 anything outside -8..=8 is a modelling mistake, not a unit"
                            ))
                        })?;
                        e as i32
                    }
                };
                let factor = Scale::new(ratio, pi);

                let offset = match t.get("offset") {
                    None => None,
                    Some(v) => {
                        let (onum, oden) = v.as_pair().ok_or_else(|| {
                            invalid(format!("[unit.{symbol}].offset must be [numerator, denominator]"))
                        })?;
                        if oden == 0 {
                            return Err(invalid(format!(
                                "[unit.{symbol}].offset has a zero denominator"
                            )));
                        }
                        Some(Rational::new(onum, oden).ok_or_else(|| {
                            invalid(format!("[unit.{symbol}].offset is not representable"))
                        })?)
                    }
                };

                if let Some(list) = t.get("aliases") {
                    let arr = list
                        .as_array()
                        .ok_or_else(|| invalid(format!("[unit.{symbol}].aliases must be an array")))?;
                    for a in arr {
                        let a = a.as_str().ok_or_else(|| {
                            invalid(format!("[unit.{symbol}].aliases entries must be strings"))
                        })?;
                        validate_symbol(a, "alias")?;
                        if let Some(prev) = aliases.insert(a.to_string(), symbol.clone()) {
                            return Err(invalid(format!(
                                "alias {a:?} is claimed by both {prev:?} and {symbol:?}"
                            )));
                        }
                    }
                }

                let display = read_display(t.get("display"));
                units.insert(
                    symbol.clone(),
                    Unit {
                        symbol: symbol.clone(),
                        dimension_name: dim_name.to_string(),
                        dimension,
                        factor,
                        offset,
                        delta: t.get("delta").and_then(Value::as_str).map(str::to_string),
                        display,
                        prefixed_from: None,
                        provenance: read_provenance(t.get("provenance")),
                    },
                );
                if let Some(v) = t.get("prefixes") {
                    let set_name = v.as_str().ok_or_else(|| {
                        invalid(format!("[unit.{symbol}].prefixes must be a string"))
                    })?;
                    prefixable_decls.push((symbol.clone(), set_name.to_string()));
                }
            }
        }

        // ---- SI prefix expansion: validated here, derived on lookup ----
        //
        // §6.1 requires prefixed units to be distinct entries so resolution never
        // has to guess whether `ft` is foot or femto-tonne. That guarantee comes
        // from *checking every combination here*, not from storing them: the
        // check is what makes ambiguity impossible, and the storage was just
        // cost. `cd` is candela and centi-day; `ft` is foot and femto-tonne —
        // any such clash is a load-time error.
        let mut prefixable: BTreeMap<String, &'static [crate::prefix::Prefix]> = BTreeMap::new();
        let mut claimed: BTreeMap<String, String> = BTreeMap::new();
        let mut shadowed: BTreeMap<String, String> = BTreeMap::new();
        for (symbol, set_name) in &prefixable_decls {
            let base = units.get(symbol).expect("declared above");
            if base.is_affine() {
                return Err(invalid(format!(
                    "[unit.{symbol}] is affine and cannot take prefixes; a prefixed \
                     degree scale is not a meaningful unit"
                )));
            }
            let set = crate::prefix::set_by_name(set_name).ok_or_else(|| {
                invalid(format!(
                    "[unit.{symbol}].prefixes = {set_name:?} is not a known prefix set \
                     (\"si\", \"si-engineering\")"
                ))
            })?;
            for (_, prefix_sym, power) in set {
                let derived = format!("{prefix_sym}{symbol}");
                validate_symbol(&derived, "expanded unit symbol")?;

                if let Some(existing) = units.get(&derived) {
                    if let Some(reason) = shadow_decls.get(&derived) {
                        // Resolved by the author: the authored unit wins this
                        // spelling, and the prefixed reading becomes unavailable
                        // rather than merely verbose (its canonical form is this
                        // very symbol). The reason travels with the decision.
                        shadowed.insert(derived.clone(), reason.clone());
                        continue;
                    }
                    let base_long = existing.display.long.as_deref().unwrap_or("");
                    let verbose = units
                        .get(symbol)
                        .and_then(|b| b.display.long.as_deref())
                        .map(|l| format!("{}{l}", prefix_long_of(set, prefix_sym)))
                        .unwrap_or_default();
                    return Err(invalid(format!(
                        "{derived:?} is ambiguous: it is an authored unit of {:?}{}, and \
                         expanding [unit.{symbol}] with prefix {prefix_sym:?} would also \
                         produce it. Resolve it here rather than leaving it to readers — \
                         either declare it under [registry.prefix_collisions] as \
                         `{derived} = \"<why the authored reading wins>\"`, which gives the \
                         authored unit the symbol and makes {} unavailable entirely (its \
                         canonical form would be {derived:?}, which now means something \
                         else), or narrow [unit.{symbol}].prefixes",
                        existing.dimension_name,
                        if base_long.is_empty() { String::new() } else { format!(" ({base_long})") },
                        if verbose.is_empty() { "the prefixed reading".to_string() } else { format!("`{verbose}`") }
                    )));
                }
                if let Some(owner) = aliases.get(&derived) {
                    return Err(invalid(format!(
                        "expanding [unit.{symbol}] produces {derived:?}, which is \
                         already an alias of {owner:?}"
                    )));
                }
                if let Some(other) = claimed.get(&derived) {
                    return Err(invalid(format!(
                        "{derived:?} is produced by expanding both {other:?} and {symbol:?}"
                    )));
                }

                // Verify the factor is representable now, so an overflow is a
                // load-time error rather than a surprise at lookup.
                let decimal = crate::prefix::decimal_factor(*power).ok_or_else(|| {
                    invalid(format!("prefix {prefix_sym:?} (10^{power}) is not representable"))
                })?;
                base.factor.checked_mul(Scale::rational(decimal)).ok_or_else(|| {
                    invalid(format!(
                        "expanding [unit.{symbol}] with prefix {prefix_sym:?} (10^{power}) \
                         overflows exact-rational range; narrow the prefix set for this unit"
                    ))
                })?;

                claimed.insert(derived, symbol.clone());
            }
            prefixable.insert(symbol.clone(), set);
        }

        // ---- verbose input aliases ----
        //
        // `MW` is unambiguous once you know the convention and opaque before
        // then, and the ASCII-only rule means `micro` is spelled `u` — which is
        // exactly the kind of detail that trips someone up once. So every unit
        // whose long name is a single word also answers to that name, and to its
        // plural: `megawatt`, `megawatts`, `microwatt`. These are ordinary
        // aliases — input-only, never emitted, and collision-checked like any
        // other.
        let mut verbose: BTreeMap<String, String> = BTreeMap::new();
        for u in units.values() {
            // Both English spellings resolve: a user should not have to guess
            // whether the registry author wrote `metre` or `meter`.
            let mut names: Vec<String> = Vec::new();
            for n in [u.display.long.as_ref(), u.display.plural.as_ref()]
                .into_iter()
                .flatten()
            {
                if let Some(a) = verbose_alias(n) {
                    if let Some(v) = crate::prefix::spelling_variant(&a) {
                        names.push(v);
                    }
                    names.push(a);
                }
            }
            for candidate in names {
                if units.contains_key(&candidate) || aliases.contains_key(&candidate) {
                    continue; // an explicit declaration always wins
                }
                if let Some(other) = verbose.get(&candidate) {
                    if other != &u.symbol {
                        return Err(invalid(format!(
                            "the name {candidate:?} is the display name of both {other:?} and \
                             {:?}; verbose input would be ambiguous",
                            u.symbol
                        )));
                    }
                    continue;
                }
                verbose.insert(candidate, u.symbol.clone());
            }
        }
        aliases.extend(verbose);

        // A spelling cannot be both refused and resolvable — the refusal would
        // never fire and the author would believe it had.
        for symbol in ambiguous.keys() {
            if units.contains_key(symbol) || aliases.contains_key(symbol) {
                return Err(invalid(format!(
                    "[registry.ambiguous] declares {symbol:?}, but this registry also defines it; \
                     a refusal that never fires is worse than none"
                )));
            }
        }

        for declared in shadow_decls.keys() {
            if !shadowed.contains_key(declared) {
                return Err(invalid(format!(
                    "[registry.prefix_collisions] declares {declared:?}, but no collision \
                     there exists; a stale entry hides the next real one"
                )));
            }
        }

        // Aliases must not shadow canonical symbols — the sneaky half of the
        // redefinition attack surface.
        for (alias, owner) in &aliases {
            if units.contains_key(alias) {
                return Err(invalid(format!(
                    "alias {alias:?} on {owner:?} collides with the canonical symbol {alias:?}"
                )));
            }
        }

        // delta integrity: target exists, shares dimension and factor, carries
        // no offset. None of this is stated normatively in the spec (AMB-018).
        for u in units.values() {
            if let Some(d) = &u.delta {
                if d == &u.symbol {
                    continue; // a non-affine unit is its own delta
                }
                let target = units.get(d).ok_or_else(|| {
                    invalid(format!("[unit.{}].delta points at undefined unit {d:?}", u.symbol))
                })?;
                if target.dimension != u.dimension {
                    return Err(invalid(format!(
                        "delta unit {d:?} does not share {:?}'s dimension",
                        u.symbol
                    )));
                }
                if target.factor != u.factor {
                    return Err(invalid(format!(
                        "delta unit {d:?} does not share {:?}'s factor",
                        u.symbol
                    )));
                }
                if target.offset.is_some() {
                    return Err(invalid(format!("delta unit {d:?} must not carry an offset")));
                }
            }
        }

        // ---- quantity kinds (§7.3) ----
        let mut quantities: BTreeMap<String, QuantityKind> = BTreeMap::new();
        if let Some(qs) = doc.get("quantity").and_then(Value::as_table) {
            for (id, body) in qs {
                let t = body
                    .as_table()
                    .ok_or_else(|| invalid(format!("[quantity.{id:?}] is not a table")))?;
                let interval = match t.get("interval") {
                    None => None,
                    // Absence is the absence of a claim, not `false` (§5.3,
                    // §8.5 rule 4) — so this stays three-valued.
                    Some(v) => Some(v.as_bool().ok_or_else(|| {
                        invalid(format!("[quantity.{id:?}].interval must be a boolean"))
                    })?),
                };
                quantities.insert(
                    id.clone(),
                    QuantityKind {
                        id: id.clone(),
                        parent: t.get("parent").and_then(Value::as_str).map(str::to_string),
                        interval,
                        rate_of: t.get("rate_of").and_then(Value::as_str).map(str::to_string),
                        summable_with: t
                            .get("summable_with")
                            .and_then(Value::as_array)
                            .map(|a| a.iter().filter_map(Value::as_str).map(str::to_string).collect())
                            .unwrap_or_default(),
                        display_long: t
                            .get("display")
                            .and_then(Value::as_table)
                            .and_then(|d| d.get("long"))
                            .and_then(Value::as_str)
                            .map(str::to_string),
                    },
                );
            }
        }

        // References resolve, and the parent graph is acyclic — §7.3 says
        // resolution is lookup with no inference engine, but `parent` is still
        // a graph and a cycle hangs a naive walker.
        for q in quantities.values() {
            for (field, target) in [("parent", &q.parent), ("rate_of", &q.rate_of)] {
                if let Some(t) = target {
                    if !quantities.contains_key(t) {
                        return Err(invalid(format!(
                            "[quantity.{:?}].{field} points at undefined kind {t:?}",
                            q.id
                        )));
                    }
                }
            }
            for s in &q.summable_with {
                if !quantities.contains_key(s) {
                    return Err(invalid(format!(
                        "[quantity.{:?}].summable_with references undefined kind {s:?}",
                        q.id
                    )));
                }
            }
        }
        for start in quantities.keys() {
            let mut seen = vec![start.clone()];
            let mut cur = quantities[start].parent.clone();
            while let Some(p) = cur {
                if seen.contains(&p) {
                    return Err(invalid(format!("quantity `parent` chain cycles at {p:?}")));
                }
                seen.push(p.clone());
                cur = quantities.get(&p).and_then(|q| q.parent.clone());
            }
        }

        Ok(Registry {
            name,
            version,
            schema_version,
            units,
            aliases,
            dimensions,
            quantities,
            prefixable,
            shadowed,
            ambiguous,
        })
    }

    /// Resolve a symbol or alias to its unit.
    ///
    /// Three branches, in precedence order:
    ///
    /// 1. an authored `[unit.…]` entry;
    /// 2. an authored or generated alias;
    /// 3. a **prefixed form**, derived here rather than stored.
    ///
    /// Branch 3 is safe to attempt only because every prefix × base combination
    /// was checked for collisions at load (see `from_toml`): an authored symbol
    /// can never also be reachable as a prefixed form, so trying explicit
    /// entries first is a fast path rather than a tie-break.
    pub fn resolve(&self, symbol: &str) -> Option<Cow<'_, Unit>> {
        if let Some(u) = self.units.get(symbol) {
            return Some(Cow::Borrowed(u));
        }
        if let Some(canonical) = self.aliases.get(symbol) {
            if let Some(u) = self.units.get(canonical) {
                return Some(Cow::Borrowed(u));
            }
            // An alias may name a prefixed form, e.g. `kilometer` -> `km`.
            return self.derive_prefixed(canonical).map(Cow::Owned);
        }
        self.derive_prefixed(symbol)
            .or_else(|| self.derive_prefixed_by_name(symbol))
            .map(Cow::Owned)
    }

    /// Resolve a *verbose* prefixed name — `megawatt`, `kilometer`,
    /// `nanometres` — by splitting it into a prefix name and a base name.
    ///
    /// The same branch as [`Self::derive_prefixed`], one level up: without it,
    /// spelling a prefixed unit out would work only for authored entries, which
    /// is exactly the inconsistency verbose input exists to remove.
    fn derive_prefixed_by_name(&self, input: &str) -> Option<Unit> {
        let lower = input.to_ascii_lowercase();
        for (base_symbol, set) in &self.prefixable {
            let base = self.units.get(base_symbol)?;
            for base_name in [base.display.long.as_ref(), base.display.plural.as_ref()]
                .into_iter()
                .flatten()
            {
                let Some(base_word) = verbose_alias(base_name) else {
                    continue;
                };
                for (long, prefix_sym, power) in *set {
                    let composed = format!("{long}{base_word}");
                    let matches = lower == composed
                        || crate::prefix::spelling_variant(&composed)
                            .is_some_and(|v| lower == v);
                    if matches {
                        // A shadowed symbol has no escape hatch, and it is worth
                        // being precise about why: the derived unit's *canonical
                        // form* is that very symbol (§6.3), which the authored
                        // unit now owns. Resolving `femtotonne` would hand back
                        // canonical `ft` — foot — so the reading is genuinely
                        // unavailable rather than merely inconvenient.
                        let symbol = format!("{prefix_sym}{base_symbol}");
                        if self.shadowed.contains_key(&symbol) {
                            return None;
                        }
                        return self.synthesize(base_symbol, long, prefix_sym, *power);
                    }
                }
            }
        }
        None
    }

    /// Every spelling in this registry that a prefix could also produce.
    ///
    /// A loaded registry has no *unresolved* risks — those are load errors — so
    /// in practice this reports what the author decided, which is exactly what a
    /// reviewer wants to see. Pair it with [`Self::would_collide`] before adding
    /// a unit.
    pub fn collision_risks(&self) -> Vec<CollisionRisk> {
        let mut out = Vec::new();
        for (base, set) in &self.prefixable {
            for (long, prefix_sym, _) in *set {
                let symbol = format!("{prefix_sym}{base}");
                let authored = self.units.get(&symbol).map(|u| u.dimension_name.clone());
                let reason = self.shadowed.get(&symbol).cloned();
                if authored.is_some() || reason.is_some() {
                    out.push(CollisionRisk {
                        symbol,
                        authored,
                        prefix: prefix_sym,
                        prefix_long: long,
                        base: base.clone(),
                        resolved: reason.is_some(),
                        reason,
                    });
                }
            }
        }
        out.sort_by(|a, b| a.symbol.cmp(&b.symbol));
        out
    }

    /// Would declaring `symbol` as a unit collide with a prefixed reading?
    ///
    /// The proactive form: check *before* adding `[unit.cd]` rather than after
    /// the load fails. Returns the reading that would contest it.
    pub fn would_collide(&self, symbol: &str) -> Option<CollisionRisk> {
        for (base, set) in &self.prefixable {
            let Some(rest) = symbol.strip_suffix(base.as_str()) else {
                continue;
            };
            if rest.is_empty() {
                continue;
            }
            for (long, prefix_sym, _) in *set {
                if rest == *prefix_sym {
                    let reason = self.shadowed.get(symbol).cloned();
                    return Some(CollisionRisk {
                        symbol: symbol.into(),
                        authored: self.units.get(symbol).map(|u| u.dimension_name.clone()),
                        prefix: prefix_sym,
                        prefix_long: long,
                        base: base.clone(),
                        resolved: reason.is_some(),
                        reason,
                    });
                }
            }
        }
        None
    }

    /// The declared refusal for a spelling, if this registry has one.
    pub fn ambiguity(&self, symbol: &str) -> Option<&Ambiguity> {
        self.ambiguous.get(symbol)
    }

    /// Every spelling this registry refuses on purpose — the material a
    /// documentation page should render, so the page the error points at is
    /// generated from the same declaration the error is.
    pub fn ambiguities(&self) -> Vec<(&str, &Ambiguity)> {
        self.ambiguous.iter().map(|(k, v)| (k.as_str(), v)).collect()
    }

    /// Which measurement conventions this registry actually contains, with a
    /// count of authored units for each.
    ///
    /// **Derived, never declared.** A registry-level `system = "us"` field was
    /// considered and rejected: real registries are mixed, so the label would
    /// be false for most of them, and a declared summary can drift from its
    /// contents exactly the way a hand-maintained count does. Summarising what
    /// the units say cannot lie.
    ///
    /// Units with no stated convention appear under `None` — that is a gap in
    /// the registry, and it should be visible rather than defaulted.
    pub fn systems(&self) -> Vec<(Option<String>, usize)> {
        let mut counts: BTreeMap<Option<String>, usize> = BTreeMap::new();
        for u in self.units.values() {
            *counts.entry(u.provenance.system.clone()).or_insert(0) += 1;
        }
        let mut out: Vec<(Option<String>, usize)> = counts.into_iter().collect();
        out.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(&b.0)));
        out
    }

    /// Authored units whose definition names no convention.
    ///
    /// The `Btu` case is why this matters: `MBtu` means 10^6 under SI prefixes
    /// and 10^3 in the US gas industry, and nothing in the symbol says which.
    /// A unit whose reading depends on a convention should say which one.
    pub fn units_without_a_stated_system(&self) -> Vec<&str> {
        let mut out: Vec<&str> = self
            .units
            .values()
            .filter(|u| u.provenance.system.is_none())
            .map(|u| u.symbol.as_str())
            .collect();
        out.sort_unstable();
        out
    }

    /// Every spelling a prefix can produce in this registry — the set a new unit
    /// symbol must avoid, or explicitly contest.
    ///
    /// This is the "reserved symbols" list a registry developer needs, and it is
    /// derived rather than fixed: it depends entirely on which units this
    /// registry made prefixable.
    pub fn prefix_reserved(&self) -> Vec<String> {
        let mut out: Vec<String> = Vec::new();
        for (base, set) in &self.prefixable {
            for (_, prefix_sym, _) in *set {
                out.push(format!("{prefix_sym}{base}"));
            }
        }
        out.sort_unstable();
        out
    }

    /// Every name this registry resolves, authored or derived.
    ///
    /// Materialised on demand — for suggestions and for documentation — rather
    /// than stored, which is the whole point of deriving prefixed forms.
    pub fn candidates(&self) -> Vec<String> {
        let mut out: Vec<String> = self.units.keys().cloned().collect();
        out.extend(self.aliases.keys().cloned());
        for (base_symbol, set) in &self.prefixable {
            let base = &self.units[base_symbol];
            for (long, prefix_sym, _) in *set {
                out.push(format!("{prefix_sym}{base_symbol}"));
                for base_name in [base.display.long.as_ref(), base.display.plural.as_ref()]
                    .into_iter()
                    .flatten()
                {
                    if let Some(word) = verbose_alias(base_name) {
                        let composed = format!("{long}{word}");
                        if let Some(v) = crate::prefix::spelling_variant(&composed) {
                            out.push(v);
                        }
                        out.push(composed);
                    }
                }
            }
        }
        out.sort_unstable();
        out.dedup();
        out
    }

    /// Every unit this registry resolves, authored or derived — for docs.
    pub fn expanded_units(&self) -> Vec<Unit> {
        let mut out: Vec<Unit> = self.units.values().cloned().collect();
        for (base_symbol, set) in &self.prefixable {
            for (_, prefix_sym, _) in *set {
                if let Some(u) = self.derive_prefixed(&format!("{prefix_sym}{base_symbol}")) {
                    out.push(u);
                }
            }
        }
        out
    }

    /// Authored units only. Use [`Self::expanded_units`] for the resolvable set.
    pub fn authored_count(&self) -> usize {
        self.units.len()
    }

    /// Build a prefixed unit from its base, or `None` if `symbol` is not one.
    ///
    /// Returns `None` for a **shadowed** spelling: there the authored unit owns
    /// the symbol, and this reading has no spelling left at all — its canonical
    /// form (§6.3) *is* the contested symbol, which now means something else.
    fn derive_prefixed(&self, symbol: &str) -> Option<Unit> {
        if self.shadowed.contains_key(symbol) {
            return None;
        }
        for (base_symbol, set) in &self.prefixable {
            // The symbol must end with this base and have something in front.
            let Some(rest) = symbol.strip_suffix(base_symbol.as_str()) else {
                continue;
            };
            if rest.is_empty() {
                continue;
            }
            for (long, prefix_sym, power) in *set {
                if rest == *prefix_sym {
                    return self.synthesize(base_symbol, long, prefix_sym, *power);
                }
            }
        }
        None
    }

    /// Construct a prefixed unit. No shadow check — the two callers reach it by
    /// different spellings (symbol and long name) and each screens for shadowing
    /// first, so folding the check in here would only duplicate it.
    fn synthesize(
        &self,
        base_symbol: &str,
        long: &str,
        prefix_sym: &str,
        power: i32,
    ) -> Option<Unit> {
        let base = self.units.get(base_symbol)?;
        let factor = base.factor.checked_mul(Scale::rational(crate::prefix::decimal_factor(power)?))?;
        Some(Unit {
            symbol: format!("{prefix_sym}{base_symbol}"),
            dimension_name: base.dimension_name.clone(),
            dimension: base.dimension,
            factor,
            offset: None,
            delta: None,
            provenance: base.provenance.clone(),
            display: DisplayForms {
                unicode: None,
                ascii: None,
                latex: None,
                long: base
                    .display
                    .long
                    .as_ref()
                    .filter(|l| verbose_alias(l).is_some())
                    .map(|l| format!("{long}{l}")),
                plural: base
                    .display
                    .plural
                    .as_ref()
                    .filter(|pl| verbose_alias(pl).is_some())
                    .map(|pl| format!("{long}{pl}")),
            },
            prefixed_from: Some(base_symbol.into()),
        })
    }

    pub fn canonical_symbol(&self, symbol: &str) -> Option<String> {
        self.resolve(symbol).map(|u| u.symbol.clone())
    }

    /// The human-readable name for a symbol — the reverse of verbose input.
    ///
    /// Worth calling after tagging: seeing `MW → megawatt` confirms you tagged
    /// the unit you meant, and `mW → milliwatt` catches the case slip that
    /// would otherwise be wrong by 10⁹ and silent.
    pub fn describe(&self, symbol: &str) -> Option<String> {
        let u = self.resolve(symbol)?;
        u.display.long.clone().or_else(|| u.display.unicode.clone())
    }

    /// Candidate symbols for an input that did not resolve.
    ///
    /// Case-insensitive matches first — `Megawatt` and `MEGAWATT` are the
    /// predictable stumble once verbose names exist, and symbols are
    /// case-sensitive by §6.1 — then near-misses by edit distance.
    pub fn suggest(&self, input: &str) -> Vec<String> {
        let lower = input.to_ascii_lowercase();
        let mut exact: Vec<String> = Vec::new();
        let mut near: Vec<(usize, String)> = Vec::new();

        for cand in self.candidates() {
            if cand == input {
                continue;
            }
            if cand.to_ascii_lowercase() == lower {
                exact.push(cand);
                continue;
            }
            let d = edit_distance(&lower, &cand.to_ascii_lowercase());
            let budget = if input.len() <= 4 { 1 } else { 2 };
            if d <= budget {
                near.push((d, cand));
            }
        }
        exact.sort_unstable();
        near.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(&b.1)));
        exact.into_iter().chain(near.into_iter().map(|(_, c)| c)).take(4).collect()
    }

    /// Reverse-lookup a **display form** to the unit it belongs to.
    ///
    /// Only forms that are not themselves legal symbols are considered — `°C`
    /// and `Δ°C` need a hint, `MW` does not. This is what lets a syntax error
    /// say "`°C` is the display form of `degC`" instead of the generic "symbols
    /// are ASCII", which leaves the user to guess the spelling.
    pub fn by_display(&self, text: &str) -> Option<&Unit> {
        self.units.values().find(|u| {
            [
                u.display.unicode.as_deref(),
                u.display.ascii.as_deref(),
                u.display.latex.as_deref(),
            ]
            .into_iter()
            .flatten()
            .any(|form| form == text && verbose_alias(form).is_none())
        })
    }

    /// Any display form appearing anywhere in `input`, with the unit it names.
    /// Used to enrich a syntax error with the spelling the user actually wants.
    pub fn display_form_in(&self, input: &str) -> Option<(&str, &Unit)> {
        let mut best: Option<(&str, &Unit)> = None;
        for u in self.units.values() {
            for form in [
                u.display.unicode.as_deref(),
                u.display.ascii.as_deref(),
                u.display.latex.as_deref(),
            ]
            .into_iter()
            .flatten()
            {
                // A form that is a legal symbol needs no hint; one that is not
                // is precisely what the user could not have typed.
                if verbose_alias(form).is_some() || !input.contains(form) {
                    continue;
                }
                if best.is_none_or(|(prev, _)| form.len() > prev.len()) {
                    best = Some((form, u));
                }
            }
        }
        best
    }

    pub fn units(&self) -> impl Iterator<Item = &Unit> {
        self.units.values()
    }

    /// Number of units this registry **resolves**, authored plus derived.
    ///
    /// Not the same as [`Self::authored_count`], and the gap is the point: a
    /// registry with 20 authored units and the full SI set resolves 500 symbols
    /// while storing 20.
    pub fn unit_count(&self) -> usize {
        self.units.len()
            + self
                .prefixable
                .values()
                .map(|set| set.len())
                .sum::<usize>()
    }

    pub fn aliases(&self) -> &BTreeMap<String, String> {
        &self.aliases
    }

    pub fn dimensions(&self) -> &BTreeMap<String, Dimension> {
        &self.dimensions
    }

    pub fn quantities(&self) -> &BTreeMap<String, QuantityKind> {
        &self.quantities
    }
}

/// A long display name is usable as a *verbose input alias* only when it is
/// already a legal symbol — a single ASCII word. "watt" qualifies; "British
/// thermal unit (IT)" does not, and inventing a spelling for it would be
/// guessing at what a user will type.
/// Levenshtein distance, for did-you-mean suggestions only.
fn edit_distance(a: &str, b: &str) -> usize {
    let a: Vec<char> = a.chars().collect();
    let b: Vec<char> = b.chars().collect();
    if a.is_empty() {
        return b.len();
    }
    let mut prev: Vec<usize> = (0..=b.len()).collect();
    let mut cur = vec![0usize; b.len() + 1];
    for (i, ca) in a.iter().enumerate() {
        cur[0] = i + 1;
        for (j, cb) in b.iter().enumerate() {
            let cost = usize::from(ca != cb);
            cur[j + 1] = (prev[j + 1] + 1).min(cur[j] + 1).min(prev[j] + cost);
        }
        core::mem::swap(&mut prev, &mut cur);
    }
    prev[b.len()]
}

/// The long name of a prefix within a set, for error messages.
fn prefix_long_of(set: &'static [crate::prefix::Prefix], sym: &str) -> &'static str {
    set.iter().find(|(_, s, _)| *s == sym).map(|(l, _, _)| *l).unwrap_or("")
}

fn verbose_alias(name: &str) -> Option<String> {
    let ok = name
        .chars()
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic())
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
    ok.then(|| name.to_ascii_lowercase())
}

fn validate_symbol(s: &str, what: &str) -> Result<()> {
    let mut chars = s.chars();
    let ok = match chars.next() {
        Some(c) if c.is_ascii_alphabetic() => {
            chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '@')
        }
        _ => false,
    };
    if !ok {
        return Err(invalid(format!(
            "{what} {s:?} is not a valid symbol; symbols are ASCII, start with a letter, and \
             continue with letters, digits, `_`, or `@` (§6.1)"
        )));
    }
    Ok(())
}

fn read_provenance(v: Option<&Value>) -> Provenance {
    let t = v.and_then(Value::as_table);
    let get = |k: &str| {
        t.and_then(|t| t.get(k))
            .and_then(Value::as_str)
            .map(str::to_string)
    };
    Provenance {
        system: get("system"),
        source: get("source"),
        scope: get("scope"),
        note: get("note"),
    }
}

fn read_display(v: Option<&Value>) -> DisplayForms {
    let t = v.and_then(Value::as_table);
    let get = |k: &str| {
        t.and_then(|t| t.get(k))
            .and_then(Value::as_str)
            .map(str::to_string)
    };
    DisplayForms {
        unicode: get("unicode"),
        ascii: get("ascii"),
        latex: get("latex"),
        long: get("long"),
        plural: get("plural"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::{format};

    const MINIMAL: &str = r#"
[registry]
schema_version = 1
name = "test"
version = "0.1.0"

[dimension.power]
vector = { mass = 1, length = 2, time = -3 }

[unit.W]
dimension = "power"
factor = [1, 1]

[unit.MW]
dimension = "power"
factor = [1000000, 1]
aliases = ["megawatt"]
"#;

    fn load(extra: &str) -> Result<Registry> {
        Registry::from_toml(&format!("{MINIMAL}{extra}"))
    }

    #[test]
    fn loads_and_resolves_aliases() {
        let r = load("").unwrap();
        assert_eq!(r.canonical_symbol("megawatt").as_deref(), Some("MW"));
        assert_eq!(r.canonical_symbol("MW").as_deref(), Some("MW"));
        assert!(r.resolve("Zorkmid").is_none());
    }

    #[test]
    fn rejects_missing_name() {
        let e = Registry::from_toml("[registry]\nschema_version = 1\nversion = \"1\"\n").unwrap_err();
        assert_eq!(e.code(), ErrorCode::RegistryInvalid);
        assert!(e.message().contains("name is required"), "{}", e.message());
    }

    #[test]
    fn rejects_degenerate_factors() {
        for (bad, hint) in [
            ("[unit.x]\ndimension = \"power\"\nfactor = [1, 0]\n", "zero denominator"),
            ("[unit.x]\ndimension = \"power\"\nfactor = [0, 1]\n", "zero scale"),
            ("[unit.x]\ndimension = \"power\"\nfactor = [-1, 1]\n", "negative scale"),
            ("[unit.x]\ndimension = \"power\"\nfactor = [1000, 10]\n", "lowest terms"),
        ] {
            let e = load(bad).unwrap_err();
            assert!(e.message().contains(hint), "expected {hint:?}, got {}", e.message());
        }
    }

    #[test]
    fn rejects_shadowing_a_canonical_symbol_by_alias() {
        let e = load("[unit.x]\ndimension = \"power\"\nfactor = [1, 1]\naliases = [\"MW\"]\n")
            .unwrap_err();
        assert!(e.message().contains("collides"), "{}", e.message());
    }

    #[test]
    fn rejects_a_symbol_that_would_break_canonical_form() {
        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [unit.\"M*W\"]\ndimension = \"mass\"\nfactor = [1, 1]\n",
        )
        .unwrap_err();
        assert!(e.message().contains("not a valid symbol"), "{}", e.message());
    }

    #[test]
    fn allows_identity_declarations_but_rejects_base_redefinition() {
        // Redundant but harmless — the conformance registry does this.
        assert!(Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [dimension.length]\nvector = { length = 1 }\n"
        )
        .is_ok());
        // A genuine redefinition silently changes every commensurability check.
        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [dimension.length]\nvector = { mass = 1 }\n"
        )
        .unwrap_err();
        assert!(e.message().contains("redefines base dimension"), "{}", e.message());
    }

    #[test]
    fn rejects_unknown_base_dimension_and_overflow() {
        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [dimension.bad]\nvector = { energy = 1 }\n",
        )
        .unwrap_err();
        assert!(e.message().contains("unknown base dimension"), "{}", e.message());

        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [dimension.big]\nvector = { length = 200 }\n",
        )
        .unwrap_err();
        assert!(e.message().contains("8-bit"), "{}", e.message());
    }

    #[test]
    fn rejects_typo_keys() {
        let e = load("[unit.y]\ndimension = \"power\"\nfactor = [1, 1]\nfactr = [2, 1]\n").unwrap_err();
        assert!(e.message().contains("unknown key"), "{}", e.message());
    }

    #[test]
    fn rejects_broken_delta_targets() {
        let e = load("[unit.z]\ndimension = \"power\"\nfactor = [1, 1]\ndelta = \"nope\"\n")
            .unwrap_err();
        assert!(e.message().contains("undefined unit"), "{}", e.message());
    }

    #[test]
    fn rejects_parent_cycles() {
        let e = load(
            "[quantity.a]\nparent = \"b\"\n[quantity.b]\nparent = \"a\"\n",
        )
        .unwrap_err();
        assert!(e.message().contains("cycles"), "{}", e.message());
    }

    #[test]
    fn prefix_expansion_computes_factors_from_one_authored_value() {
        let r = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [dimension.power]\nvector = { mass = 1, length = 2, time = -3 }\n\
             [unit.W]\ndimension = \"power\"\nfactor = [1, 1]\nprefixes = \"si-engineering\"\n\
             display = { long = \"watt\" }\n",
        )
        .unwrap();
        // One authored entry stays one stored entry; the other twelve are
        // derived on lookup. That is the point of the branch.
        assert_eq!(r.authored_count(), 1);
        assert_eq!(r.expanded_units().len(), 13);
        // The range reaches the units this project's own domain needs.
        assert_eq!(r.resolve("PW").unwrap().factor, Rational::integer(1_000_000_000_000_000).into());
        assert_eq!(r.resolve("kW").unwrap().factor, Rational::integer(1000).into());
        assert_eq!(r.resolve("MW").unwrap().factor, Rational::integer(1_000_000).into());
        assert_eq!(r.resolve("TW").unwrap().factor, Rational::integer(1_000_000_000_000).into());
        assert_eq!(r.resolve("mW").unwrap().factor, Rational::new(1, 1000).unwrap().into());
        assert_eq!(r.resolve("uW").unwrap().factor, Rational::new(1, 1_000_000).unwrap().into());
        // Long display names compose.
        assert_eq!(r.resolve("kW").unwrap().display.long.as_deref(), Some("kilowatt"));
        // Generated entries know where they came from.
        assert_eq!(r.resolve("GW").unwrap().prefixed_from.as_deref(), Some("W"));
        assert!(r.resolve("W").unwrap().prefixed_from.is_none());
    }

    #[test]
    fn expansion_collision_with_an_explicit_unit_is_an_error() {
        // `ft` is foot; expanding tonne with femto would also produce `ft`.
        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [unit.ft]\ndimension = \"length\"\nfactor = [381, 1250]\n\
             [unit.t]\ndimension = \"mass\"\nfactor = [1000, 1]\nprefixes = \"si-engineering\"\n",
        )
        .unwrap_err();
        assert_eq!(e.code(), ErrorCode::RegistryInvalid);
        assert!(e.message().contains("is ambiguous"), "{}", e.message());
        assert!(e.message().contains("\"ft\""), "{}", e.message());
    }

    #[test]
    fn expansion_collision_with_an_alias_is_an_error() {
        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [unit.hour]\ndimension = \"time\"\nfactor = [3600, 1]\naliases = [\"kg\"]\n\
             [unit.g]\ndimension = \"mass\"\nfactor = [1, 1000]\nprefixes = \"si-engineering\"\n",
        )
        .unwrap_err();
        assert!(e.message().contains("already an alias"), "{}", e.message());
    }

    #[test]
    fn expansion_overflow_is_refused_not_wrapped() {
        // Btu survives the full SI range, which is *not* obvious: 10^30 x
        // 52752792631 is 5.3e40, well past i128 — but Rational cross-reduces
        // before multiplying, and Btu's denominator (5e7) cancels 10^7 of the
        // prefix, landing at 1.055e33. Exact arithmetic buys real headroom here.
        assert!(Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [dimension.energy]\nvector = { mass = 1, length = 2, time = -2 }\n\
             [unit.Btu]\ndimension = \"energy\"\nfactor = [52752792631, 50000000]\n\
             prefixes = \"si\"\n"
        )
        .is_ok());

        // A large numerator over a denominator of 1 gives cross-reduction
        // nothing to work with, and quetta then overflows for real.
        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [dimension.energy]\nvector = { mass = 1, length = 2, time = -2 }\n\
             [unit.bigJ]\ndimension = \"energy\"\nfactor = [52752792631, 1]\n\
             prefixes = \"si\"\n",
        )
        .unwrap_err();
        assert!(e.message().contains("overflows"), "{}", e.message());
        assert!(e.message().contains("narrow the prefix set"), "{}", e.message());

        // ...and the engineering subset keeps the same unit comfortably inside range.
        assert!(Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [dimension.energy]\nvector = { mass = 1, length = 2, time = -2 }\n\
             [unit.bigJ]\ndimension = \"energy\"\nfactor = [52752792631, 1]\n\
             prefixes = \"si-engineering\"\n"
        )
        .is_ok());
    }

    #[test]
    fn affine_units_cannot_be_prefixed() {
        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [unit.degC]\ndimension = \"temperature\"\nfactor = [1, 1]\n\
             offset = [27315, 100]\nprefixes = \"si-engineering\"\n",
        )
        .unwrap_err();
        assert!(e.message().contains("affine and cannot take prefixes"), "{}", e.message());
    }

    #[test]
    fn an_unknown_prefix_set_is_rejected() {
        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [unit.m]\ndimension = \"length\"\nfactor = [1, 1]\nprefixes = \"imperial\"\n",
        )
        .unwrap_err();
        assert!(e.message().contains("not a known prefix set"), "{}", e.message());
    }

    #[test]
    fn verbose_names_resolve_and_reverse() {
        let r = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [dimension.power]\nvector = { mass = 1, length = 2, time = -3 }\n\
             [unit.W]\ndimension = \"power\"\nfactor = [1, 1]\nprefixes = \"si-engineering\"\n\
             display = { long = \"watt\", plural = \"watts\" }\n",
        )
        .unwrap();

        // Forward: spell it out instead of guessing the symbol.
        for (verbose, symbol) in [
            ("watt", "W"),
            ("watts", "W"),
            ("megawatt", "MW"),
            ("megawatts", "MW"),
            ("microwatt", "uW"),
            ("terawatt", "TW"),
            ("milliwatt", "mW"),
        ] {
            assert_eq!(r.canonical_symbol(verbose).as_deref(), Some(symbol), "for {verbose}");
        }

        // Reverse: confirm a tag means what you think it means. This is the
        // check that catches mW/MW — wrong by 10^9 and otherwise silent.
        assert_eq!(r.describe("MW").as_deref(), Some("megawatt"));
        assert_eq!(r.describe("mW").as_deref(), Some("milliwatt"));
        assert_eq!(r.describe("uW").as_deref(), Some("microwatt"));
    }

    #[test]
    fn suggestions_cover_the_predictable_stumbles() {
        let r = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [dimension.power]\nvector = { mass = 1, length = 2, time = -3 }\n\
             [unit.W]\ndimension = \"power\"\nfactor = [1, 1]\nprefixes = \"si-engineering\"\n\
             display = { long = \"watt\", plural = \"watts\" }\n",
        )
        .unwrap();
        // Wrong case — symbols are case-sensitive, so this needs a nudge.
        assert!(r.suggest("Megawatt").iter().any(|c| c == "megawatt"));
        assert!(r.suggest("MEGAWATT").iter().any(|c| c == "megawatt"));
        // Typo.
        assert!(r.suggest("megwatt").iter().any(|c| c == "megawatt"));
        // Nothing plausible, no noise.
        assert!(r.suggest("Zorkmid").is_empty());
    }

    #[test]
    fn an_explicit_alias_beats_a_generated_verbose_name() {
        let r = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [unit.h]\ndimension = \"time\"\nfactor = [3600, 1]\naliases = [\"hour\"]\n\
             display = { long = \"hour\" }\n",
        )
        .unwrap();
        assert_eq!(r.canonical_symbol("hour").as_deref(), Some("h"));
    }

    #[test]
    fn two_units_sharing_a_display_name_is_an_error() {
        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [unit.a]\ndimension = \"mass\"\nfactor = [1, 1]\ndisplay = { long = \"gram\" }\n\
             [unit.b]\ndimension = \"mass\"\nfactor = [2, 1]\ndisplay = { long = \"gram\" }\n",
        )
        .unwrap_err();
        assert!(e.message().contains("verbose input would be ambiguous"), "{}", e.message());
    }

    #[test]
    fn multiword_display_names_do_not_become_aliases() {
        let r = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [dimension.energy]\nvector = { mass = 1, length = 2, time = -2 }\n\
             [unit.Btu]\ndimension = \"energy\"\nfactor = [52752792631, 50000000]\n\
             display = { long = \"British thermal unit (IT)\" }\n",
        )
        .unwrap();
        // No spelling is invented for a name that is not a legal symbol.
        assert!(r.canonical_symbol("British thermal unit (IT).as_deref()").is_none());
        assert!(r.aliases().is_empty());
        // The reverse direction still works, which is what it is for.
        assert_eq!(r.describe("Btu").as_deref(), Some("British thermal unit (IT)"));
    }

    #[test]
    fn both_english_spellings_resolve() {
        let r = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [unit.m]\ndimension = \"length\"\nfactor = [1, 1]\nprefixes = \"si-engineering\"\n\
             display = { long = \"metre\", plural = \"metres\" }\n",
        )
        .unwrap();
        for (input, symbol) in [
            ("metre", "m"), ("meter", "m"), ("metres", "m"), ("meters", "m"),
            ("kilometre", "km"), ("kilometer", "km"),
            ("nanometre", "nm"), ("nanometer", "nm"),
        ] {
            assert_eq!(r.canonical_symbol(input).as_deref(), Some(symbol), "for {input}");
        }
        // The registry's own choice is still what displays.
        assert_eq!(r.describe("km").as_deref(), Some("kilometre"));
    }

    #[test]
    fn a_us_spelling_registry_also_accepts_both() {
        // Symmetric: whichever the author picked, both resolve.
        let r = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [unit.L]\ndimension = \"length\"\nfactor = [1, 1]\n\
             display = { long = \"liter\" }\n",
        )
        .unwrap();
        assert_eq!(r.canonical_symbol("liter").as_deref(), Some("L"));
        assert_eq!(r.canonical_symbol("litre").as_deref(), Some("L"));
        assert_eq!(r.describe("L").as_deref(), Some("liter"));
    }

    #[test]
    fn ton_and_tonne_are_never_related() {
        // Different units — 1000 kg vs 907.18474 kg. A generic -re/-er rule
        // would alias them and be silently wrong by 10%.
        let r = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [unit.t]\ndimension = \"mass\"\nfactor = [1000, 1]\ndisplay = { long = \"tonne\" }\n\
             [unit.ton]\ndimension = \"mass\"\nfactor = [45359237, 50000]\n\
             display = { long = \"ton\" }\n",
        )
        .unwrap();
        assert_eq!(r.canonical_symbol("tonne").as_deref(), Some("t"));
        assert_eq!(r.canonical_symbol("ton").as_deref(), Some("ton"));
        assert_ne!(r.resolve("t").unwrap().factor, r.resolve("ton").unwrap().factor);
    }

    #[test]
    fn an_unresolved_collision_names_the_fix() {
        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [unit.ft]\ndimension = \"length\"\nfactor = [381, 1250]\n\
             display = { long = \"foot\" }\n\
             [unit.t]\ndimension = \"mass\"\nfactor = [1000, 1]\n\
             prefixes = \"si-engineering\"\ndisplay = { long = \"tonne\" }\n",
        )
        .unwrap_err();
        let m = e.message();
        assert!(m.contains("is ambiguous"), "{m}");
        assert!(m.contains("[registry.prefix_collisions]"), "{m}");
        assert!(m.contains("why the authored reading wins"), "the reason is asked for: {m}");
        assert!(m.contains("femtotonne"), "the sacrificed reading is named: {m}");
        assert!(m.contains("unavailable entirely"), "the cost is stated: {m}");
    }

    #[test]
    fn a_declared_collision_gives_the_authored_unit_the_spelling() {
        let r = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [registry.prefix_collisions]\n\
             ft = \"foot is ubiquitous here; femto-tonne is not a real quantity\"\n\
             [unit.ft]\ndimension = \"length\"\nfactor = [381, 1250]\n\
             display = { long = \"foot\" }\n\
             [unit.t]\ndimension = \"mass\"\nfactor = [1000, 1]\n\
             prefixes = \"si-engineering\"\ndisplay = { long = \"tonne\" }\n",
        )
        .unwrap();

        // The common spelling means the common thing. No user is asked.
        assert_eq!(r.describe("ft").as_deref(), Some("foot"));
        assert_eq!(r.resolve("ft").unwrap().dimension_name, "length");

        // Everything else about the prefixed unit still works — this is why
        // narrowing the prefix set would have been the wrong fix.
        assert!(r.resolve("kt").is_some(), "kilotonne survives");
        assert!(r.resolve("Mt").is_some(), "megatonne survives");

        // The shadowed reading is unavailable, and that is correct rather than
        // a limitation: its canonical form would be `ft`, which now means foot.
        // A verbose "escape hatch" would hand back a canonical string meaning
        // something else — silently.
        assert!(r.resolve("femtotonne").is_none());
        assert!(r.resolve("ft").is_some_and(|u| u.dimension_name == "length"));
    }

    #[test]
    fn a_stale_collision_declaration_is_rejected() {
        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [registry.prefix_collisions]\n\
             ft = \"foot is ubiquitous here; femto-tonne is not a real quantity\"\n\
             [unit.m]\ndimension = \"length\"\nfactor = [1, 1]\n",
        )
        .unwrap_err();
        assert!(e.message().contains("no collision"), "{}", e.message());
    }

    #[test]
    fn a_registry_reports_what_a_new_symbol_would_contest() {
        let r = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [unit.t]\ndimension = \"mass\"\nfactor = [1000, 1]\n\
             prefixes = \"si-engineering\"\ndisplay = { long = \"tonne\" }\n",
        )
        .unwrap();

        // The proactive check: ask before declaring, not after the load fails.
        let risk = r.would_collide("ft").expect("ft is contested");
        assert_eq!((risk.prefix, risk.prefix_long, risk.base.as_str()), ("f", "femto", "t"));
        assert!(risk.authored.is_none(), "nothing declared there yet");
        assert!(!risk.resolved);

        // A symbol nothing can produce is free.
        assert!(r.would_collide("mile").is_none());
        assert!(r.would_collide("t").is_none(), "the base itself is not a collision");

        // The full reserved set is derived from what this registry made
        // prefixable — it is not a fixed list.
        let reserved = r.prefix_reserved();
        assert!(reserved.contains(&"ft".to_string()));
        assert!(reserved.contains(&"kt".to_string()));
        assert_eq!(reserved.len(), 12, "one per prefix in the set");
    }

    #[test]
    fn resolved_collisions_are_reportable_for_review() {
        let r = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [registry.prefix_collisions]\n\
             ft = \"foot is ubiquitous here; femto-tonne is not a real quantity\"\n\
             [unit.ft]\ndimension = \"length\"\nfactor = [381, 1250]\n\
             display = { long = \"foot\" }\n\
             [unit.t]\ndimension = \"mass\"\nfactor = [1000, 1]\n\
             prefixes = \"si-engineering\"\ndisplay = { long = \"tonne\" }\n",
        )
        .unwrap();
        let risks = r.collision_risks();
        assert_eq!(risks.len(), 1, "exactly one judgement call in this registry");
        let ft = &risks[0];
        assert_eq!(ft.symbol, "ft");
        assert_eq!(ft.authored.as_deref(), Some("length"));
        assert_eq!(ft.prefix_long, "femto");
        assert!(ft.resolved, "the author decided this one");
        // The review question is "why", not "what" — a reader of the diff can
        // see `[unit.ft]` was added but not that it cost `femtotonne`.
        assert_eq!(
            ft.reason.as_deref(),
            Some("foot is ubiquitous here; femto-tonne is not a real quantity")
        );
    }

    #[test]
    fn a_collision_cannot_be_resolved_without_saying_why() {
        // The bare-list form is what a registry author reaches for first, so the
        // rejection has to teach the replacement rather than just refuse.
        let list = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             prefix_collisions = [\"ft\"]\n\
             [unit.ft]\ndimension = \"length\"\nfactor = [381, 1250]\n\
             [unit.t]\ndimension = \"mass\"\nfactor = [1000, 1]\n\
             prefixes = \"si-engineering\"\n",
        )
        .unwrap_err();
        assert!(list.message().contains("must be a table"), "{}", list.message());
        assert!(list.message().contains("ft = "), "shows the shape: {}", list.message());

        // An empty reason is the same omission with extra steps.
        let blank = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"t\"\nversion = \"1\"\n\
             [registry.prefix_collisions]\n\
             ft = \"   \"\n\
             [unit.ft]\ndimension = \"length\"\nfactor = [381, 1250]\n\
             [unit.t]\ndimension = \"mass\"\nfactor = [1000, 1]\n\
             prefixes = \"si-engineering\"\n",
        )
        .unwrap_err();
        assert!(blank.message().contains("empty reason"), "{}", blank.message());
    }

    #[test]
    fn a_refused_spelling_explains_itself_instead_of_looking_like_a_typo() {
        let r = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"g\"\nversion = \"1\"\n\
             [registry.ambiguous.MBtu]\n\
             reason = \"M is mega under SI and the Roman thousand in the US gas industry\"\n\
             use = [\"MMBtu\"]\n\
             see = \"https://example.invalid/ambiguity\"\n\
             [dimension.energy]\nvector = { mass = 1, length = 2, time = -2 }\n\
             [unit.Btu]\ndimension = \"energy\"\nfactor = [52752792631, 50000000]\n",
        )
        .expect("loads");

        let e = crate::canonicalize("MBtu", &r, 1).unwrap_err();
        let m = e.message();
        // The three things a user needs: that it was refused deliberately, why,
        // and what to write instead.
        assert!(m.contains("refused rather than guessed"), "{m}");
        assert!(m.contains("Roman thousand"), "the reason travels: {m}");
        assert!(m.contains("`MMBtu`"), "the fix is named: {m}");
        assert!(m.contains("https://example.invalid/ambiguity"), "points at docs: {m}");
        // And it must NOT read as a typo.
        assert!(!m.contains("did you mean"), "a deliberate refusal is not a typo: {m}");

        // An ordinary unknown symbol still gets the suggestion path.
        let typo = crate::canonicalize("Btuu", &r, 1).unwrap_err();
        assert!(typo.message().contains("does not resolve"), "{}", typo.message());
    }

    #[test]
    fn a_refusal_without_a_reason_is_rejected() {
        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"g\"\nversion = \"1\"\n\
             [registry.ambiguous.MBtu]\nreason = \"  \"\n\
             [unit.m]\ndimension = \"length\"\nfactor = [1, 1]\n",
        )
        .unwrap_err();
        assert!(e.message().contains("non-empty `reason`"), "{}", e.message());
    }

    #[test]
    fn a_refusal_that_could_never_fire_is_rejected() {
        // Declaring a spelling refused while also defining it means the refusal
        // is dead code and the author would believe it was protecting them.
        let e = Registry::from_toml(
            "[registry]\nschema_version = 1\nname = \"g\"\nversion = \"1\"\n\
             [registry.ambiguous.m]\nreason = \"ambiguous somehow\"\n\
             [unit.m]\ndimension = \"length\"\nfactor = [1, 1]\n",
        )
        .unwrap_err();
        assert!(e.message().contains("also defines it"), "{}", e.message());
    }

    #[test]
    fn loads_the_conformance_registry() {
        let src = std::fs::read_to_string(
            concat!(env!("CARGO_MANIFEST_DIR"), "/../../conformance/registry/conformance-core.toml"),
        )
        .expect("conformance registry present");
        let r = Registry::from_toml(&src).expect("conformance registry is valid");
        assert_eq!(r.name, "conformance-core");
        assert!(r.unit_count() >= 15);
        // The AMB-016 ruling, asserted on real data.
        let degf = r.resolve("degF").unwrap();
        assert_eq!(degf.offset.unwrap(), Rational::new(45967, 180).unwrap());
        assert_eq!(r.canonical_symbol("F").as_deref(), Some("degF"));
    }
}
